version: '3.8'

services:
  register:
    build:
      context: ./register
    image: joeli2104/register:latest
    ports:
      - "2001:2001"
    networks:
      - responsible_network

  update-responsible:
    build:
      context: ./update-responsible
    image: joeli2104/update-responsible:latest
    ports:
      - "2002:2002"
    networks:
      - responsible_network

  get-responsible-by-id:
    build:
      context: ./get-responsible-by-id
    image: joeli2104/get-responsible-by-id:latest
    ports:
      - "2003:2003"
    networks:
      - responsible_network

  get-all-eesponsibles:
    build:
      context: ./get-all-responsibles
    image: joeli2104/get-all-responsibles:latest
    ports:
      - "2004:2004"
    networks:
      - responsible_network

  delete-responsible:
    build:
      context: ./delete-responsible
    image: joeli2104/delete-responsible:latest
    ports:
      - "2005:2005"
    networks:
      - responsible_network

  upload-avatar:
    build:
      context: ./upload-avatar
    image: joeli2104/upload-avatar:latest
    ports:
      - "2006:2006"
    networks:
      - responsible_network
  
  update-avatar:
    build:
      context: ./update-avatar
    image: joeli2104/update-avatar:latest
    ports:
      - "2007:2007"
    networks:
      - responsible_network

  get-all-avatars:
    build:
      context: ./get-all-avatars
    image: joeli2104/get-all-avatars:latest
    ports:
      - "2009:2009"
    networks:
      - responsible_network

  delete-avatar:
    build:
      context: ./delete-avatar
    image: joeli2104/delete-avatar:latest
    ports:
      - "2008:2008"
    networks:
      - responsible_network
networks:
  responsible_network:
    driver: bridge
